# Generated by Django 4.1.7 on 2023-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_shippingaddress_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.ImageField(null=True, upload_to="products/%y/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="digital",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
